M48
; DRILL file {KiCad 9.0.6} date 2026-05-09T11:50:28+0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-09T11:50:28+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X111.91Y-58.83
T2
X98.5Y-126.0
X98.75Y-45.75
X179.25Y-126.25
X179.5Y-46.0
M30
